server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false



  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 500
    response-cache-update-interval-ms: 500